### ISSUE TITLE
Several text styles not rendering in header image

### ISSUE THREAD

**Issue by kattni** [leviarista/github-profile-header-generator#1]
Hello! Thank you for putting this tool together! I was able to create a lovely header image for my profile.

Here's the issue I am experiencing. The Title font and Subtitle font dropdowns both have several fonts that show up as an identical serif font. Basically every font from Athiti through Lifesavers shows up the same. The fonts before and after that section of the list all show up properly. Perhaps it's related to me not having those fonts locally, but I don't think I have Red Hat Display locally, and that seems to work.

I wanted to let you know in case it's an actual bug, and not simply an issue on my machine.

Thanks again!

**Comment by leviarista** [comment]
Hi Kattni, thanks for reporting this issue.

So let me explain how font loading works: 
The _Red Hat Display_ and _Kalam_ fonts are loaded by default on the page, but the other fonts are loaded dynamically. 
If that font already exists on your machine, the tool will use it (that's why some fonts like _Arial_ work for you normally), but if the font doesn't exist, the tool will load it from the assets.

It is possible that your browser is blocking this fonts loading, or maybe some kind of blocking extension, also this could be related to the OS.

Would you mind sharing this info please?:

- Your Operatiing System
- Browser 
- Any relevant extension installed?
- If possible, a screenshot of your browser console will help.

And thank you so much for using the tool , your GH header looks great! 😊.

**Comment by leviarista** [comment]
Hey! thank you very much for sharing the tool! I really appreciate it 🤗.

> Firefox 102.0.1 (64-bit)

And thanks for sharing that info, I've been testing and that font change doesn't work right in Firefox but I'll be working on it and let you know when it's fixed.

Thnaks again for reporting the issue!

**Comment by leviarista** [comment]
Hey @kattni, issue fixed!

Just to let you know, this was because I'm using the [__FontFaceSet.check__](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check) method to check if the font exists, but it returns _true_ for unkown fonts in Firefox, and returns _false_ in Chrome.

So I removed that checking and now it works in Firefox.

That problem has already been reported [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1252821), and it's because Firefox is following the draft version of the W3C standard and Chrome is following the TR version of the W3C standard. 

And [here](https://drafts.csswg.org/css-font-loading-3/#font-face-set-check) is the description of the method, you can check the second special case that is related to what happened.

**Comment by kattni** [comment]
@leviarista Fixed for me! Thank you so much for being responsive to this. I really appreciate all the info. Cheers!
